POST http://localhost:8080/api/wilders HTTP/1.1
content-type: application/json

{
    "name": "Louis",
    "city": "Paris",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}